### PR TITLE
Add GitHub Actions CI pipeline and gitignore

### PR DESCRIPTION
**Pull request by ddugovic**
Also add a test for `parse_game` based upon a handicap game I played.

### CODE REVIEW

**Comment by agt-the-walker** [comment]
Thanks, very interesting!

**Comment by ddugovic** [comment]
Oops, I didn't realize you already had a Travis CI!

Either way Actions has been useful for linting and testing my own projects.

**Comment by agt-the-walker** [comment]
I've never used Actions before. Does it support multiple languages like the current .travis.yml?

**Comment by ddugovic** [comment]
Yes, for example in my fork I added a C++ workflow (but got stuck on the libboost configuration):
https://github.com/ddugovic/shogi-utils/actions

**Pull request merged**
